version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/local/bin/app
    ports:
      - "8080:8080"
      - "80:80"
    expose:
      - "8080"
      - "80"